name: Nightly Cleanup

on:
  schedule:
    # Run at 3:00 AM UTC every day
    - cron: '0 3 * * *'
  workflow_dispatch:
    # Allow manual triggering

jobs:
  cleanup:
    name: Run Cleanup Suite
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      
      - name: Run Cleanup Suite
        run: |
          python agents/cleanup-suite/agent.py --silent
      
      - name: Upload cleanup report
        uses: actions/upload-artifact@v3
        with:
          name: cleanup-report
          path: |
            logs/maintenance/cleanup-suite-report-*.md
          retention-days: 14